### ISSUE TITLE
Extensive usage of direct links in articles

### ISSUE THREAD

**Issue by Levitanious** [Levitanious/cmangos-docs#4]
Direct links are fine when you need to point towards certain file in one of the external repos, but pointing directly to wiki like in [Home.md](../blob/master/Home.md) is going to cause all sorts of confusion and mischief.

**Solution:**
For github, at least, you can use `[Link text](../blob/master/<filename>)` or `[Link text](../wiki/<article name>)`. [Example](../wiki/Coding-Standards)

**Comment by Muehe** [comment]
Partly solved by 56397bb0f3e8f8b6650ebfd6b7b259a372870516. Links inside the Wiki are now relative, so the Wiki on this repo is now usable without checking every link first.

**Comment by Levitanious** [comment]
So, after recent commits, you think it's pretty solved and can be closed?

**Comment by Muehe** [comment]
Yeah probably. If there is any remaining stuff, like links to documentation in core repo, we should create dedicated issues for that.
